name: fraudguard
version: "1.0.0"
config-version: 2

profile: fraudguard

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: target
clean-targets:
  - target
  - dbt_packages
  - logs

vars:
  use_fixtures: false

models:
  fraudguard:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["staging"]

    intermediate:
      +schema: intermediate
      +materialized: view
      +tags: ["intermediate"]

    marts:
      core:
        +schema: core
        +materialized: table
        +tags: ["core"]
      ml:
        +schema: ml
        +materialized: table
        +tags: ["ml", "training"]
      analytics:
        +schema: analytics
        +materialized: table
        +tags: ["analytics", "superset"]

    monitoring:
      +schema: monitoring
      +materialized: table
      +tags: ["monitoring"]

seeds:
  fraudguard:
    +schema: seeds
    +quote_columns: false